---
- name: php repository gpg key (stretch only)
  become: yes
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present
  when: raspbian_version.stdout == 'stretch'

- name: php repository (stretch only)
  become: yes
  apt_repository:
    repo: deb https://packages.sury.org/php/ stretch main
    filename: php7.list
    state: present
  when: raspbian_version.stdout == 'stretch'

- name: install nginx
  become: yes
  apt:
    update_cache: no
    name: nginx

- name: install php
  become: yes
  apt:
    update_cache: no
    name:
      - php7.2-fpm
      - php7.2-sqlite3

- name: install composer
  become: yes
  apt:
    update_cache: no
    name: composer

- name: nginx config file
  become: true
  template:
    src: nginx_default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: web directory
  become: true
  file:
    path: "{{ web_home }}"
    state: directory
    owner: pi
    group: www-data
    mode: 0775

- name: public directory
  file:
    path: "{{ web_home }}/public"
    state: directory
    owner: pi
    group: www-data
    mode: 0775

- name: config directory
  file:
    path: "{{ web_home }}/Config"
    state: directory
    owner: pi
    group: www-data
    mode: 0775

- name: php config file
  template:
    src: Config.php.j2
    dest: "{{ web_home }}/Config/Config.php"
    owner: pi
    group: www-data
    mode: 0644
...
