---
- name: install composer
  become: yes
  apt:
    update_cache: no
    name: composer

- name: install nginx
  become: yes
  apt:
    update_cache: no
    name: nginx

- name: nginx config file
  become: true
  template:
    src: nginx_default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: web directory
  become: true
  file:
    path: "{{ web_home }}"
    state: directory
    owner: pi
    group: www-data
    mode: 0775

- name: public directory
  file:
    path: "{{ web_home }}/public"
    state: directory
    owner: pi
    group: www-data
    mode: 0775

- name: images directory
  file:
    path: "{{ web_home }}/public/images"
    state: directory
    owner: pi
    group: www-data
    mode: 0775

- name: audio directory
  file:
    path: "{{ web_home }}/public/audio"
    state: directory
    owner: pi
    group: www-data
    mode: 0775

- name: noaa audio directory
  file:
    path: "{{ web_home }}/public/audio/noaa"
    state: directory
    owner: pi
    group: www-data
    mode: 0775

- name: meteor audio directory
  file:
    path: "{{ web_home }}/public/audio/meteor"
    state: directory
    owner: pi
    group: www-data
    mode: 0775

- name: config directory
  file:
    path: "{{ web_home }}/Config"
    state: directory
    owner: pi
    group: www-data
    mode: 0775

- name: php config file
  template:
    src: Config.php.j2
    dest: "{{ web_home }}/Config/Config.php"
    owner: pi
    group: www-data
    mode: 0644
...
